name: installscope-comment
on:
  workflow_run:
    workflows: ["installscope"]
    types: [completed]
permissions:
  pull-requests: write
  contents: read
  actions: read
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mukti-sys/InstallScope/action/comment@f4d58d21f104a6aa3d52e1904b117f32654004d3
